- name: Install redshift on Arch Linux
  pacman:
    name: redshift
  when: ansible_facts['os_family'] == "ArchLinux"
  become: true
- name: Install redshift on Debian
  apt:
    name: redshift
  when: ansible_facts['os_family'] == "Debian"
  become: true
- name: Check if redshift config exist
  stat:
    path: "{{ global.dotfiles_dir }}/.config/redshift.conf"
  register: tint2
- name: Link redshift config
  file:
    src: "{{ global.dotfiles_dir }}/.config/redshift.conf"
    dest: "{{ global.home }}/.config/redshift.conf"
    owner: "{{ global.user }}"
    state: link
  when: not tint2.stat.exists