- name: Install tint2 on Archlinux
  pacman:
    name: tint2
  when: ansible_facts['os_family'] == "Archlinux"
  become: true
- name: Install tint2 on Debian
  apt:
    name: tint2
  when: ansible_facts['os_family'] == "Debian"
  become: true
- name: Check if exist tint2 directory
  stat:
    path: "{{ global.home }}/.config/tint2"
  register: tint2
- name: Link tint2 config
  file:
    src: "{{ global.dotfiles_dir }}/.config/tint2"
    dest: "{{ global.home }}/.config/tint2"
    owner: "{{ global.user }}"
    state: link
  when: not tint2.stat.exists