version: '3'

volumes:
  grafana:
    driver: local

services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - "grafana:/var/lib/grafana"
    restart: unless-stopped
