# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.8.0"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.synced_folder "./data", "/vagrant"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end

  config.disksize.size = '20GB'

  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.cpus = 2
    v.memory = 2048
  end
  
end
