---
- hosts: localhost
  vars:
    use_yadm: yes

  tasks:
    - name: Import global variables
      include_vars:
        file: "env.yml"
        name: global
    - name: Install Neovim and dependencies on Arch
      pacman:
        name:
        - curl
        - neovim
        - nodejs
        - npm
        - prettier
      become: yes
      when: ansible_facts["os_family"] == "Archlinux"
    - name: Install Debian and dependencies on Debian
      apt:
        name:
        - curl
        - nodejs
        - npm
        - neovim
      become: yes
      when: ansible_facts["os_family"] == "Debian"
    - name: Install prettier on Debian
      npm:
        name: prettier
        global: yes
      become: yes
      when: ansible_facts["os_family"] == "Debian"
    - name: Import YADM tasks
      import_tasks: modules/yadm.yml
      when: use_yadm
    - name: Import wittano-dotfiles
      import_tasks: modules/dotfiles.yml
      when: not use_yadm
    - name: Link neovime config from wittano-dotfiles to config directory
      file:
        src: "{{ global.config_dir }}/.config/nvim"
        dest: "{{ global.home }}/.config/nvim"
        owner: "{{ global.user }}"
        state: link
      when: not use_yadm
    - name: Install vim-plug
      command: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    - name: Install plugins
      command: nvim -c ':PlugInstall' -c 'qa!'
    - name: Install coc.nvim extensions
      command: nvim -c ':CocInstall coc-json coc-clangd coc-cmake coc-docker coc-sh coc-html coc-json coc-tsserver coc-yaml coc-prettier' -c ':qa!'
