- name: Check if gtk2 config is exist
  stat:
    path: "{{ global.home }}/.config/gtk-2.0"
  register: gtk2
- name: Check if gtk3 config is exist
  stat:
    path: "{{ global.home }}/.config/gtk-3.0"
  register: gtk3
- name: Check if gtk4 config is exist
  stat:
    path: "{{ global.home }}/.config/gtk-4.0"
  register: gtk4
- name: Link gtk2 config
  file:
    src: "{{ global.config_dir }}/.config/gtk-2.0"
    dest: "{{ global.home }}/.config/gtk-2.0"
    owner: "{{ global.user }}"
    state: link
  when: not gtk2.stat.exists
- name: Link gtk3 config
  file:
    src: "{{ global.config_dir }}/.config/gtk-3.0"
    dest: "{{ global.home }}/.config/gtk-3.0"
    owner: "{{ global.user }}"
    state: link
  when: not gtk3.stat.exists
- name: Link gtk4 config
  file:
    src: "{{ global.config_dir }}/.config/gtk-4.0"
    dest: "{{ global.home }}/.config/gtk-4.0"
    owner: "{{ global.user }}"
    state: link
  when: not gtk4.stat.exists
