- name: Install nitrogen on Arch Linux
  pacman:
    name: nitrogen
  when: ansible_facts['os_family'] == 'ArchLinux'
  become: true
- name: Install nitrogen on Debian
  apt:
    name: nitrogen
  when: ansible_facts['os_family'] == 'Debian'
  become: true
- name: Get current nitrogen config directory
  stat:
    path: "{{ global.home }}/.config/nitrogen"
  register: nitrogen
- name: Link nitrogen config
  file:
    src: "{{ global.dotfiles_dir }}/.config/nitrogen"
    dest: "{{ global.home }}/.config/nitrogen"
    state: link
  when: not nitrogen.stat.exists
- name: Chekc if directory with wallpapaers is exist
  stat:
    path: "{{ global.home }}/wallpaper"
  register: wallpapaer
- name: Link wallpapaers directory
  file:
    src: "{{ global.dotfiles_dir }}/wallpaper"
    dest: "{{ global.home }}/wallpaper"
    state: link
  when: not wallpapaer.stat.exists