version: '3'

services:
  pihole-exporter:
    container_name: "pihole-exporter"
    image: ekofr/pihole-exporter:v0.3.0
    ports:
      - "9617:9617"
    environment:
      PIHOLE_HOSTNAME: '192.168.1.8'
      PIHOLE_API_TOKEN: '062022cb35630beb942efd2bb306103ef5f4e46397db7baa315a33e6e5b5e2ae'
      ARCH: 'arm'
