---
- hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: Update pacman
      command: pacman -Syu --noconfirm
      become: yes
    - name: Install essentially packages
      pacman:
        name:
          - base-devel
          - git
          - ansible
          - vim
