---
- hosts: localhost
  vars:
    dracula_theme: yes

  tasks:
    - name: Import global variables
      include_vars:
        file: "env.yml"
        name: global
    - name: Install openbox dependences on Arch Linux
      pacman:
        name:
          - openbox
          - notify-osd
          - flameshot
          - xautolock
          - nautilus
          - obconf
          - vivaldi
          - unzip
          - lxappearance
      when: ansible_facts['os_family'] == "Archlinux"
      become: true
    - name: Install openbox dependences on Debian
      apt:
        name:
          - openbox
          - notify-osd
          - flameshot
          - xautolock
          - nautilus
          - obconf
          - unzip
          - openbox-menu
          - lxappearance
        update-cache: yes
      when: ansible_facts['os_family'] == "Debian"
      become: true
    - name: Check if Vivalid browser is installed
      stat:
        path: /usr/bin/vivaldi-stable
      register: vivaldi
    - name: Install Vivalid browser on Debian
      apt:
        deb: https://downloads.vivaldi.com/stable/vivaldi-stable_5.1.2567.57-1_amd64.deb
      when: 
        - ansible_facts['os_family'] == "Debian"
        - not vivaldi.stat.exists
      become: true
    - name: Check if config directory is exist
      stat:
        path: "{{ global.home }}/.config"
      register: config
    - name: Create home config directory
      file:
        path: "{{ global.home }}/.config"
        state: directory
      when: not config.stat.exists
    - name: Check if openbox directory is exist
      stat:
        path: "{{ global.home }}/.config/openbox"
      register: openbox
    - name: Install openbox configuration
      file:
        src: "{{ global.config_dir }}/.config/openbox"
        dest: "{{ global.home }}/.config/openbox"
        state: link
        owner: "{{ global.user }}"
      when: not openbox.stat.exists
    # TODO: Added openbox-menu installation from AUR. https://github.com/kewlfft/ansible-aur
    - name: Import dracula theme
      import_tasks: themes/dracula.yml
      when: dracula_theme
    - name: Import tint2 tasks
      import_tasks: modules/tint2.yml
    - name: Import redshift tasks
      import_tasks: modules/redshift.yml
    - name: Import nitrogen tasks
      import_tasks: modules/nitrogen.yml
    - name: Import rofi tasks
      import_tasks: modules/rofi.yml
    - name: Import gtk config tasks
      import_tasks: modules/gtk.yml
    - name: Import terminator config tasks
      import_tasks: modules/terminator.yml