---
- hosts: localhost
  vars:
    dracula_theme: yes
    use_yadm: yes

  tasks:
    - name: Import global variables
      include_vars:
        file: "env.yml"
        name: global
    - name: Import YADM tasks
      import_tasks: modules/yadm.yml
      when: use_yadm
    - name: Install openbox dependences on Arch Linux
      pacman:
        name:
          - base-devel
          - git
          - openbox
          - notify-osd
          - flameshot
          - xautolock
          - nautilus
          - obconf
          - vivaldi
          - unzip
          - terminator
          - lxappearance
          - tint2
          - volumeicon
      when: ansible_facts['os_family'] == "Archlinux"
      become: true
    - name: Check if yay manager exists
      stat:
        path: /usr/bin/yay
      register: yay
      when: ansible_facts['os_family'] == "Archlinux"
    - name: Clone yay package manager for ArchLinux
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: /tmp/yay
        owner: "{{ global.user }}"
      when:
      - ansible_facts['os_family'] == "Archlinux"
      - not yay.stat.exists
    - name: Install yay
      command: cd /tmp/yay && makepkg -si --noconfirm
      when:
      - ansible_facts['os_family'] == "Archlinux"
      - not yay.stat.exists
    - name: Install openbox dependences on Debian
      apt:
        name:
          - git
          - openbox
          - notify-osd
          - flameshot
          - xautolock
          - nautilus
          - obconf
          - unzip
          - openbox-menu
          - lxappearance
          - terminator
          - tint2
          - volumeicon-alsa
        update-cache: yes
      when: ansible_facts['os_family'] == "Debian"
      become: true
    - name: Check if Vivalid browser is installed
      stat:
        path: /usr/bin/vivaldi-stable
      register: vivaldi
    - name: Install Vivalid browser on Debian
      apt:
        deb: https://downloads.vivaldi.com/stable/vivaldi-stable_5.1.2567.57-1_amd64.deb
      become: true
      when: 
        - ansible_facts['os_family'] == "Debian"
        - not vivaldi.stat.exists
    - name: Check if config directory exists
      stat:
        path: "{{ global.home }}/.config"
      register: config
    - name: Create home config directory
      file:
        path: "{{ global.home }}/.config"
        state: directory
      when: not config.stat.exists
    - name: Check if openbox directory is exist
      stat:
        path: "{{ global.home }}/.config/openbox"
      register: openbox
      when: not use_yadm
    - name: Install openbox configuration
      file:
        src: "{{ global.dotfiles_dir }}/.config/openbox"
        dest: "{{ global.home }}/.config/openbox"
        state: link
        owner: "{{ global.user }}"
      when: 
        - not use_yadm
        - not openbox.stat.exists
    - name: Install openbox-menu on ArchLinux
      command: yay --noconfirm --noprogressbar --needed --noconfirm --sync openbox-menu
    - name: Import dracula theme
      import_tasks: themes/dracula.yml
      when: dracula_theme
    - name: Import tint2 tasks
      import_tasks: modules/tint2.yml
      when: not use_yadm
    - name: Import redshift tasks
      import_tasks: modules/redshift.yml
      when: not use_yadm
    - name: Import nitrogen tasks
      import_tasks: modules/nitrogen.yml
      when: not use_yadm
    - name: Import rofi tasks
      import_tasks: modules/rofi.yml
      when: not use_yadm
    - name: Import gtk config tasks
      import_tasks: modules/gtk.yml
      when: not use_yadm
    - name: Import terminator config tasks
      import_tasks: modules/terminator.yml
      when: not use_yadm
      