---
- hosts: localhost,

  tasks:
    - name: Import global variables
      include_vars:
        file: "env.yml"
        name: global
    - name: Install zsh on Arch Linux
      pacman:
        name:
          - zsh
          - curl
      become: true
      when: ansible_facts['os_family'] == "Archlinux"
    - name: Install zsh on Debian
      apt:
        name:
          - zsh
          - curl
      become: true
      when: ansible_facts['os_family'] == "Debian"
    - name: Install 'oh-my-zsh'
      shell:
        cmd: "/usr/bin/curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash"
        creates: "{{ global.home }}/.oh-my-zsh"
    - name: Check .zshrc is deployed
      stat:
        path: "{{ global.home }}/.zshrc"
      register: zsh_config
    - name: Depoly zsh config
      file:
        src: "{{ global.config_dir }}/.zshrc"
        dest: "{{ global.home }}/.zshrc"
        owner: "{{ global.user }}"
        state: link
      when: not zsh_config.stat.exists
    - name: Change user shell to zsh
      become: yes
      user:
        name: "{{ global.user }}"
        shell: /bin/zsh
