---
- hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: Replace bullseye repo by unstable(sid) repo
      replace:
        path: /etc/apt/sources.list
        regexp: "bullseye main$"
        replace: "sid main contrib non-free"
    - name: Upgrade system
      apt:
        update_cache: yes
        upgrade: dist
    - name: Install essentially packages
      apt:
        name:
          - git
          - ansible
          - vim
    - name: Create ansible config directory
      file:
        path: /etc/ansible
        state: directory
    - name: Set Ansible pretty debug output
      blockinfile:
        path: /etc/ansible/ansible.cfg
        create: yes
        block: |
          [defaults]
          stdout_callback = debug
