---
- hosts: all
  become: yes
  tasks:
  - name: Install additional repos
    dnf:
      name: epel-release
      state: latest
  - name: Install essentialy packages
    dnf:
      name:
        - ansible
        - vim
      state: latest
