# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/8"

  config.vm.synced_folder "data", "/vagrant", type: "rsync"
  # config.vm.synced_folder "data", "/vagrant"

  config.disksize.size = '20GB'

  # config.vm.network "private_network", ip: "192.168.1.2"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 2048
    vb.cpus = 1
  end
end
