# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/gentoo"

  config.vm.synced_folder "data", "/vagrant"

  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.memory = "4096"
    v.cpus = 3
  end
  
end
