# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "esselius/nixos"
  config.vm.synced_folder "./data", "/vagrant"

  config.vm.provision "shell", path: "install.sh"

  config.disksize.size = '50GB'

  config.vm.provider "virtualbox" do |v|
    v.memory = "8192"
    v.cpus = 3
  end

end

